### ISSUE TITLE
Audioread.NoBackendError

### ISSUE THREAD

**Issue by Yeongtae** [Rayhane-mamah/Tacotron-2#127]
I'm trying to run 'wavenet_preprocess.py'.
When I use ' python wavenet_preprocess.py --input_dir='LJSpeech-1.1', I can see an error.

![image](https://user-images.githubusercontent.com/13597229/43782098-790d73b0-9a99-11e8-9fe4-ad7aca34b4a5.png)

I'm using tf18, py36 with a conda environment.
Though I installed requirements using 'conda install -c conda-forge ffmpeg pygobject' to solve the error
and the test code of 'audioread'  is work well
![image](https://user-images.githubusercontent.com/13597229/43782314-0b090a2c-9a9a-11e8-91f8-99bc2a577f0c.png)

**, I can't fix it.**

please update 'requirement.txt' to solve the problem.

**Comment by Rayhane-mamah** [comment]
Hey @Yeongtae thanks for reaching out! 

It has been a while since I last tested the `wavenet_preprocess.py`, let me check this out for you. You will get some feedback in a few hours.

**Comment by Rayhane-mamah** [comment]
@Yeongtae could you provide your `audioread` real quick?

**Comment by Rayhane-mamah** [comment]
I have added my version of `audioread` to the requirements if the issue is coming from there.
You may also want to simply use your conda's environment pip to install the requirements (I use anaconda too).

In any case, if things are not fixed, here is my setup, googling the issue isn't too useful..:
- Ubuntu 16.04
- Tensorflow 1.7.1
- All the rest just like "requirements.txt"

Let me know if you get it fixed.

**Comment by Rayhane-mamah** [comment]
This seems to be solved, glad it all worked out.
