### ISSUE TITLE
Test synthesize.py, Dimension mismatch

### ISSUE THREAD

**Issue by Yeongtae** [Rayhane-mamah/Tacotron-2#149]
![image](https://user-images.githubusercontent.com/13597229/43999756-9e7db60c-9e4d-11e8-9853-e5351d7d915c.png)

Do i need to retrain wavenet model?

**Comment by Yeongtae** [comment]
When i train the wavenet using previous checkpoint, the same error occurs.

**Comment by Yeongtae** [comment]
![image](https://user-images.githubusercontent.com/13597229/43999891-d87ac824-9e50-11e8-84d3-ae42ff43b497.png)
Retraining is fine.

**Comment by Yeongtae** [comment]
In my opinion, this part make this error.
There is a need to modify this part. 

![image](https://user-images.githubusercontent.com/13597229/44000172-3a9291ea-9e56-11e8-9c22-60fa857ba02f.png)

**Comment by Rayhane-mamah** [comment]
I think there's a version issue? could you please verify you have all files up to date? I believe those are the lines you screenshot? 
https://github.com/Rayhane-mamah/Tacotron-2/blob/350d5e123532383c22f8e96258a306b2bdb7f6eb/wavenet_vocoder/models/wavenet.py#L334-L337

We changed to synthesizing in batches (default is 8), so the initial value needs to be a vector of 8 matrices. Your wavenet.py doesn't seem up to date on that.

**Comment by Yeongtae** [comment]
![image](https://user-images.githubusercontent.com/13597229/44000845-18890fa0-9e62-11e8-9616-d7ff7197891d.png)

Above thing is my mistake. I am using your latest commit.

**Comment by Yeongtae** [comment]
It is fine using a sentence.
But I found another error.
![image](https://user-images.githubusercontent.com/13597229/44001235-4d228096-9e69-11e8-841d-71debc687cc2.png)

**Comment by Rayhane-mamah** [comment]
Hello again @Yeongtae,

I fixed the last bug (padding clipping bug). As for the first bug however, I didn't manage to reproduce using both multiple versions: many synthesis inputs, single synthesis input..

The [1, 1, 512] shape is assuming you are getting only 1 inputs instead of a batch.. I can't quite figure out the steps you followed to get to that behavior, so please provide exacts steps to reproduce?

**Comment by Yeongtae** [comment]
Python synthsize.py --text_list='test.txt'

In test.txt
Have a nice weekend.

**Comment by Yeongtae** [comment]
1. git clone your latest commit
2. copy logs-Tacotorn-2 directory, that has trained tacotron, wavenet checkpoints with 'mulaw-quntize 256'
3. change hparams.py
![image](https://user-images.githubusercontent.com/13597229/44006261-3d9c22e6-9ebc-11e8-9a65-32f47e57aba9.png)
![image](https://user-images.githubusercontent.com/13597229/44006263-4778cdbe-9ebc-11e8-8b21-3858486c3c1e.png)
4. run python synthesize.py 
![image](https://user-images.githubusercontent.com/13597229/44006298-25e1d9a6-9ebd-11e8-8e69-e489ce954d87.png)
>> it seems to not work the parameter 'tacotron synthesize batch'.

**Comment by Rayhane-mamah** [comment]
Tacotron only synthesizes in batches when it is a GTA synthesis because we know the lengths of mels so we know how to clip the final outputs to eliminate paddings. As for simple synthesis (like in evaluation mode), we only have text information so we cannot know in advance the length of mels. Thus we synthesize one at a time.

For wavenet, we always know the output length as it is mel_length * hop size so we can synthesize in batches. 

About your dimension mismatch, I figure it was with "mulaw-quantize", you confirmed this right now, Could you try something real quick? (I need to redo preprocessing to test it, so if you test it and it fixes it I will push this right away):
Could you replace the "1" in this line to "batch_size" please and retry?
https://github.com/Rayhane-mamah/Tacotron-2/blob/ffeca51f9196c8a013bed017276cd16c1a9c2956/wavenet_vocoder/models/wavenet.py#L618

I believe that's what's making it bug with "mulaw-quantize", we need to sample "batch_size" samples for each time step instead of only 1 sample. Let me know how this goes.

**Comment by Rayhane-mamah** [comment]
I have run the test, it looks like it's making the job correctly. Feel free to reopen if this is persistent ;)
