### ISSUE TITLE
Long batch generation times

### ISSUE THREAD

**Issue by blacksph3re** [Rayhane-mamah/Tacotron-2#236]
I try to train the latest version of the repo on a machine with 8 CPUs, 2 V100, 24GB Ram.  The repo spends a significant time reading stuff from disk, resulting in high batch generation times:

`Generated 64 train batches of size 64 in 249.438 sec`

I can't put the training data into a ramfs as I don't have enough ram for that. Has anyone encountered (and solved) this problem already?

**Comment by alexdemartos** [comment]
Hi, I'm having the same problem with the last commit (multi-GPU training):

`Generated 64 train batches of size 48 in 291.479 sec`

**Comment by alexdemartos** [comment]
Seems that this only happens for early steps in training. After some time, it stabilizes and goes down to ~10s

**Comment by blacksph3re** [comment]
I believe that's because your operating system cached the training data files into memory and you don't have the read accesses anymore. I also tried increasing RAM and it solved the problem. 
So for anyone else: It is advisable to have enough RAM to store the entire training dataset and the models and stuff in memory for faster training times. Maybe it could be possible to do batch generation asynchronously in the future?

**Comment by gloriouskilka** [comment]
Hello, @blacksph3re 

> Maybe it could be possible to do batch generation asynchronously in the future?

As far as i understand, there is already tf.FIFOQueue https://github.com/Rayhane-mamah/Tacotron-2/blob/970b0803bb41e68cbac854dc958dbb03f34f9604/tacotron/feeder.py#L85
which then filling in here https://github.com/Rayhane-mamah/Tacotron-2/blob/970b0803bb41e68cbac854dc958dbb03f34f9604/tacotron/feeder.py#L169 which is another thread https://github.com/Rayhane-mamah/Tacotron-2/blob/970b0803bb41e68cbac854dc958dbb03f34f9604/tacotron/feeder.py#L113

Personally, I increased FIFOQueue's capacity (8) because I have not much data

**Comment by blacksph3re** [comment]
That solved it, thanks!
