### ISSUE TITLE
Strange alignment when training model

### ISSUE THREAD

**Issue by toannhu** [Rayhane-mamah/Tacotron-2#32]
First of all, thank you for great implementation of Tacotron 2. I'm trying to training Vietnamese language with my own dataset. The dataset is 22.05kHz, about 6 hours, already trimmed all silence. But I couldn't see any alignment of the model? Is it the problem?

![step-24000-align](https://user-images.githubusercontent.com/19307982/39227118-0cd474d8-4881-11e8-9b87-d6e0dbcf38ed.png)

![step-24000-pred-mel-spectrogram](https://user-images.githubusercontent.com/19307982/39227097-f611e244-4880-11e8-8224-0cf13c81423a.png)

![step-24000-real-mel-spectrogram](https://user-images.githubusercontent.com/19307982/39227100-f7cde556-4880-11e8-9395-45a681d9bd4a.png)

![step-25500-align](https://user-images.githubusercontent.com/19307982/39227110-06fa556e-4881-11e8-88a6-27199eff939c.png)

![step-25500-pred-mel-spectrogram](https://user-images.githubusercontent.com/19307982/39227125-11b29f48-4881-11e8-8223-417eebcdca95.png)

![step-25500-real-mel-spectrogram](https://user-images.githubusercontent.com/19307982/39227128-11ee301c-4881-11e8-99dc-8eea525123da.png)

[sound.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/1945500/sound.zip)

Thanks for helping me!

**Comment by gloriouskilka** [comment]
I noticed same results with 
```
outputs_per_step = 1
tacotron_batch_size = 64
```

model training on CPU
![step-120-align](https://user-images.githubusercontent.com/12680403/39252608-3a0026ce-48d0-11e8-8917-9cdafb81829d.png)
![step-120-pred-mel-spectrogram](https://user-images.githubusercontent.com/12680403/39252609-3a28f23e-48d0-11e8-8296-06641dc083ea.png)
![step-120-real-mel-spectrogram](https://user-images.githubusercontent.com/12680403/39252610-3a4d5dd6-48d0-11e8-9fff-9377cdc2d5e2.png)

Other model trains on GPU on the same data, looks OK. GPU hparams are the same except for:
```
outputs_per_step = 5
tacotron_batch_size = 32
```

**Comment by Rayhane-mamah** [comment]
Hmmm there's a lot I could think of that can cause this..

First, let's talk about architecture, are you using the exact same
architecture I am using for english?

Second, I see that there's a data point where there are around 1200
decoding steps, are most of your data that large? It's usually harder for
the model to to make proper alignments on long sentences.

I also noticed that there is too much padding, could you try optimizing
that? Are you bot using something similar to our data feeder?

Finally, 6 hours of data seems like a small dataset.. I wondet if that can
impact that.

There are however few cases where my model started giving similar attention
before learning the proper one.

Feel free to show me your hparams.py along with any changes you made to the
project.

Also could you approximately tell me how much Memory the r=1, batch_size=64
consumed? Thanks

**Comment by gloriouskilka** [comment]
> Also could you approximately tell me how much Memory the r=1, batch_size=64
consumed? Thanks

@Rayhane-mamah It consumes ~10Gb of RAM. OOMed few hours ago. I have 24Gb RAM total in the machine, I don't know how much it tried to allocate before OOM. I'll make batch size 32 now

PS I'm not a topic starter, just noticed the same picture with alignment and noticed the difference in my hparams, maybe it'll help with the initial problem.

**Comment by Rayhane-mamah** [comment]
Oh my bad I didn't pay attention.. really sorry about that..

Thanks for your feedback however :)

**Comment by toannhu** [comment]
@Rayhane-mamah 
1. About my dataset, I format exactly same like LJSpeech (`wavs` folder and `metadata.csv`) but I use `basic_cleaners` and change `_character` into 186 symbols (Ex: `aáàạảã`... etc...)
2. The audio length varies from 1s -> 9s but mostly from 5s-7s. I also trimmed all leading and trailing silence and all silence < 50db inside the audio. I'm sorry that I couldn't understand what you mean "there is too much padding, could you try optimizing that?" (I'm just a newbie in TTS o.0). Could you enlighten me how to do this thing?
Btw I use default `hparams.py` except 
`outputs_per_step = 1
tacotron_batch_size = 8`
When I started training I got OOMed problem in some first steps just like @gloriouskilka said but then it's gone and loss decrease very fast.

**Comment by toannhu** [comment]
Btw, if I change all text_input into lowercase and remove all `!?,.'"`, I think it will decrease vector input size. Will this thing help the alignment model?

**Comment by Rayhane-mamah** [comment]
No actually I think I know the reason.. I had experienced failure cases
where the model couldn't learn attention with batch_size smaller than 32.

If your gpu can't work with higher batch size than your current then you
should probably try to find the lowest outputs_per_step possible that
supports batch_size=32.

Also in order to reduce memory usage effectively, do you see that long dark
part in the mel spectrograms you reported? They are paddings (const values
we add to sequences to make them all of the same length to be able to make
matrix computations effevtively).

These paddings are non existant in original data and thus should be
minimized because it's mostly useless. In our data feeder, we try grouping
sentences with similar lengths which allows to have minor differences
between sequences in the same batch, so paddings are rarely larger than 20
steps. (In the second example you gave it has 500 frames of padding).

Optimizing that can make you win some memory and model quality. I am
currently working on the wavenet and hopefully using a reduction factor
larger than 1 won't affect quality much.

**Comment by toannhu** [comment]
Tks. I'll try and report to you later 😄

**Comment by al3chen** [comment]
on my GTX1080(8G) ,for LJSpeech , 
 outputs_per_step=2 and batch_size=32 is good after 30k steps .
 outputs_per_step=1 and batch_size=32, OOM.
 outputs_per_step=1 and batch_size=16,  fail after 30k steps.

**Comment by begeekmyfriend** [comment]
r==2 is acceptable for me. I do not think there is difference in synthesized audio quality between r==1 and r==2.

**Comment by toannhu** [comment]
First of all, thank you everyone for helping me out. I succeed in training my own Vietnamese corpus (r = 2 and batch_size=16, OOM few steps then alignments show up around step 16000) 
![step-16000-align](https://user-images.githubusercontent.com/19307982/40339938-cacb1e4e-5da6-11e8-9887-bbd6ee091de1.png)
![step-16500-align](https://user-images.githubusercontent.com/19307982/40339940-cbf70f8a-5da6-11e8-877e-b8faa50db8ff.png)
I have some questions want to ask you guys
1. The synthesis sound is so good and naturalness but it seems a little bit faster than the original data. Is that because the attention module? And what the difference between content-based attention and location-based attention? What is the attention use in this Tacotron 2 implementation?
2. What is the information that I can read from the mel-spectrogram here? How to compare 2 spectrogram?
![step-258000-real-mel-spectrogram](https://user-images.githubusercontent.com/19307982/40340119-a08a71ba-5da7-11e8-861b-917072017a7b.png)
![step-258000-pred-mel-spectrogram](https://user-images.githubusercontent.com/19307982/40340120-a189e122-5da7-11e8-95aa-b39b9c4ce407.png)
3. Is the wavenet vocoder in this repo ready for training? I'm earger to hear the result synthesis from Tacotron 2 + Wavenet Vocoder.

**Comment by toannhu** [comment]
BTW, I have some strange alignment in some step here
![1](https://user-images.githubusercontent.com/19307982/40341796-55b28f74-5db1-11e8-9cdd-dd12f573a4e9.png)
![2](https://user-images.githubusercontent.com/19307982/40341797-55e4299e-5db1-11e8-9513-1ecc4387fc19.png)

**Comment by toannhu** [comment]
@Rayhane-mamah Here are some few samples 
https://soundcloud.com/dinh-toan-nhu/sets/tacotron-2
https://soundcloud.com/dinh-toan-nhu/speech-wav-00006-mel
Once again, thanks for your help :)

**Comment by Rayhane-mamah** [comment]
@toannhu thanks for the samples! 

For mel spectrograms, as mentioned in the paper we model our mel spectrograms on 80 dimensions. i.e: for each mel frame, we have a vector of dimension [1(i.e: one time step), 80] so the y axis values are 0 -> 80.

As for the smoothness of the spectrogram, I assure you are referring to the blur? It is mainly caused by the fact that the model is minimizing the MSE as mentioned in the T2 paper:
" This is due to the tendency of the predicted spectrograms to be oversmoothed and less detailed than the ground truth – a consequence of the squared error loss optimized by the feature prediction network".

I am not 100% sure about what makes the MSE the cause of these oversmoothed features, but it should be no problem for the wavenet to be conditioned on mels generated using r=2 since we already know for a [fact](https://github.com/Rayhane-mamah/Tacotron-2/issues/30#issuecomment-387261800) that r=3 also works properly.

**Comment by butterl** [comment]
outputs_per_step = 3 ，while batch=32  gives fast alignment for me
and bigger outputs_per_step led to faster alignment  but slow loss reduction

**Comment by toannhu** [comment]
@Rayhane-mamah  I tried to intergrate Tacotron 2 with r9y9's WaveNet Vocoder using his Google Colab's code but it failed. The pitch has been lost. Btw, I use `batch_size = 16` and `r=2` in Tacotron 2 and `batch_size = 1` in WaveNet. Wavenet Repo is training with original sound not with GTA. Here are the results.
[sound.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2042475/sound.zip)

**Comment by Rayhane-mamah** [comment]
@toannhu we fixed our wavenet implementation in case you want to give it a go. You can also Wavenet with GTA for best audio quality. Problems of quality that come from wavenet mostly rely on that. and you may want to train the wavenet for 1 million steps if using "raw" mode.

Feel free to reopen the issue if needed.
