### ISSUE TITLE
Help a Noob train Tacotron 2 

### ISSUE THREAD

**Issue by rohan6366** [Rayhane-mamah/Tacotron-2#340]
Can someone guide me through training Tacotron 2 with my own data. I have wavs and txt of the files. Further, how do I do voice adaption? I do not have much data

**Comment by alexdemartos** [comment]
This repo is prepared to process data as provided by LJSpeech data corpus. It is a good idea that you process your own data in order to generate a metadata.csv file (in the same way LJSpeech has it), and a wavs folder with your audio files.

If your corpus is small, it would be best to train with external data first (LJSpeech, M-AILABS), and once you reach a full trained model, use your own data to fine tune it. If you're training an english system, you can first train with LJSpeech and then fine tune with your training data. There is a boolean flag to enable fine tuning training in hparams.py.

In addition, depending on your hardware (no. GPUs, GPU RAM), you would need to toy around with some parameters like batch size and outputs per step.
