### ISSUE TITLE
Time steps different in dataset preprocessed between Tacotron and WaveNet repo

### ISSUE THREAD

**Issue by butterl** [Rayhane-mamah/Tacotron-2#54]
@Rayhane-mamah  I tried using Tacotron2  GTA  to feed  @r9y9  Wavenet  as training data 
(using tacotron preprocessed speech-audio-XXX.npy and GTA speech-mel-XXX.npy to compare different with real wav trained wavenet model output)
and I  found  assert in 
```
def assert_ready_for_upsampling(x, c):
    #print("len x = %d, len(c) = %d", len(x),len(c))
    assert len(x) % len(c) == 0 and len(x) // len(c) == audio.get_hop_size()
```
tried removed the assert check, the wavenet train eval became full sharp noise after 10K and which should give voice like wave plot at 10K with wavenet generated training data

Then I checked the train.txt generated from the two repo， the wav time steps are not same for same audio . In the audio.py of two repos the code routine are little different
Tacotron-2 : 
```
	mel_spectrogram = audio.melspectrogram(wav, hparams).astype(np.float32)
	mel_frames = mel_spectrogram.shape[1]  #<<===========N using shape[1] here
.......
	#Ensure time resolution adjustment between audio and mel-spectrogram
	l, r = audio.pad_lr(wav, hparams.fft_size, audio.get_hop_size(hparams))

	#Zero pad for quantized signal
	out = np.pad(out, (l, r), mode='constant', constant_values=constant_values)
	time_steps = len(out)                                 #<<=========== init timesteps here
	assert time_steps >= mel_frames * audio.get_hop_size(hparams)

	#time resolution adjustement
	#ensure length of raw audio is multiple of hop size so that we can use
	#transposed convolution to upsample
	out = out[:mel_frames * audio.get_hop_size(hparams)]
	assert time_steps % audio.get_hop_size(hparams) == 0

```
Wavenet repo :
```
    # Compute a mel-scale spectrogram from the trimmed wav:
    # (N, D)
    mel_spectrogram = audio.melspectrogram(wav).astype(np.float32).T
    # lws pads zeros internally before performing stft
    # this is needed to adjust time resolution between audio and mel-spectrogram
    l, r = audio.lws_pad_lr(wav, hparams.fft_size, audio.get_hop_size())

    # zero pad for quantized signal
    out = np.pad(out, (l, r), mode="constant", constant_values=constant_values)
    N = mel_spectrogram.shape[0]              #<<===========N using shape[0] here
    assert len(out) >= N * audio.get_hop_size()

    # time resolution adjustment
    # ensure length of raw audio is multiple of hop_size so that we can use
    # transposed convolution to upsample
    out = out[:N * audio.get_hop_size()]
    assert len(out) % audio.get_hop_size() == 0

    timesteps = len(out)   #<<=========== init timesteps here
```
maybe this is reason why time step are different， but I’m not sure if this is a design different or just a mistake here.

**Comment by Rayhane-mamah** [comment]
Hello @butterl thanks for reaching out!

I am aware Wavenet can't be used with GTA mels yet, I reported this [here](https://github.com/Rayhane-mamah/Tacotron-2/issues/4#issuecomment-390441188). 

Now, I wasn't successful in locating the cause yet, but starting on your steps is surely a good idea. about the differences:
- I select `mel_frames` with `shape[1]` because I am storing mels as `[80, frames]` unlike Wavenet repo which stores them `[frames, 80]`.
- about the time_steps: it's true that if out is cropped, we don't get same time_steps value, I am however not sure if it's the problem to fix GTA. I'll have to check it out. 

Side Note: By the way I still have not tested Wavenet on Ground Truth mels (been busy lately), so we don't know for sure that Wavenet is working correctly yet :)

**Comment by butterl** [comment]
find in the new repo， set  output per step =2 and  it will eat up all memory but the GPU usage seem not very high. Does it mean the feeder side is not working at full speed？ 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:06.0 Off |                    0 |
| N/A   34C    P0    28W / 250W |      0MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  Off  | 00000000:00:07.0 Off |                    0 |
| N/A   60C    P0    71W / 250W |  15641MiB / 16276MiB |     43%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by a3626a** [comment]
GPU utilization / Memory consumption depends on `output_per_step`. Are you using same `output_per_step` value for the 'old version'?

**Comment by butterl** [comment]
@a3626a  yes， output_per_step is the same between the different versions

**Comment by Rayhane-mamah** [comment]
After doing some checks here and there, I do confirm that `outputs_per_step` affects the GPU utilization and that the slowdowns are mainly caused by the recursive nature of the model, nothing I can do to make full profit of the GPU power..

To know if the feeder is causing the slowdown or not @butterl you should keep track of your disk usage as well (feeder slowdowns are mainly caused by lecture from disk). Also, if the feeder is the problem, you would probably notice slow batch generations as well (reported in the terminal, from my experience, generating 32 batches of 48 takes 1.8~2 sec).

@butterl could you point me to the "older version" you're referring to? I will try figuring out the source of the slowdown for you.

**Comment by butterl** [comment]
Generated 32 train batches of size 48 in 2.151 sec  seems the disk is little slow
and the older version is  around this [commit](https://github.com/Rayhane-mamah/Tacotron-2/commit/c1a4109430ed22047535d3ee6a0712a9920f33a7)
