### ISSUE TITLE
Rescaling WAV before training?

### ISSUE THREAD

**Issue by ghost** [Rayhane-mamah/Tacotron-2#69]
hi, 
I do not know why the WAV should be rescaled during the preprocessing procedure, in this way:
```
if hparams.rescale:
		wav = wav / np.abs(wav).max() * hparams.rescaling_max
```
Could you tell me why, or is there any keyword I could search via Google? Thank you so much.

**Comment by Rayhane-mamah** [comment]
Just going to add something on @harlyh brilliant answer (thanks for that)

We rescale because it is assumed in Wavenet training that wavs are in [-1, 1] when computing the mixture loss. This is mainly coming from [PixelCNN](https://github.com/openai/pixel-cnn/blob/master/pixel_cnn_pp/nn.py) implementation.

hope this answers your question :)
