### ISSUE TITLE
LJ Data vs M-AILABS data

### ISSUE THREAD

**Issue by Jeff-Winchell** [Rayhane-mamah/Tacotron-2#88]
On my memory challenged machine, the loss rate at a given step is MUCH lower for LJ data than the AILabs data. I have after just 2000 steps a loss rate of about .6 whereas I've never gotten much below a loss rate of 1.0 after 10,000 steps with any part of the AILABS data set.

On the other hand, the M-AILABS data showed the diagonal alignment more clearly (even if the slope was 4+ instead of 1. The LJ data barely shows anything on the graph, except that the implied slope given the two axis maxiums is roughly 2/3 (vs the 4+ on M-AILABS data).

This may have to do with using higher outputs_per_steps values on the AILABs data. (If only the program would stop falling asleep I could test more variations).

Has anyone else compared the two data sets? 
This makes me wonder how successful I will be when I go through the effort of aligning text and chopping up recordings into small times for the dataset I really want to use.

**Comment by Rayhane-mamah** [comment]
Hey again Jeff.

Like we discussed this once before I think, I'm leaving the answer here for others.
M-AILABS is noisier, that's true, but also the loss values computed are not normed in any way and they are absolute, so comparison is somewhat inaccurate since the two datasets probably don't have exact same output distributions (due to speaker nature).

I hope this answers it. cheers!
